#!/usr/bin/env node

/**
 * 自动检测并配置最快的镜像源
 * 支持: npm registry, sharp, better-sqlite3, puppeteer
 *
 * 用法: node scripts/setup-mirror.mjs
 */

import { writeFileSync, existsSync, appendFileSync, readFileSync } from 'fs';
import { execSync } from 'child_process';

// 镜像源配置 (主1备2兜底1)
const MIRRORS = {
  registry: [
    { name: 'npmmirror', url: 'https://registry.npmmirror.com', test: 'https://registry.npmmirror.com' },
    { name: 'huawei', url: 'https://mirrors.huaweicloud.com/repository/npm/', test: 'https://mirrors.huaweicloud.com/repository/npm/' },
    { name: 'npmjs', url: 'https://registry.npmjs.org', test: 'https://registry.npmjs.org' }
  ],
  sharp: [
    { name: 'npmmirror', url: 'https://registry.npmmirror.com/-/binary/sharp', test: 'https://registry.npmmirror.com/-/binary/sharp' },
    { name: 'github', url: 'https://github.com/lovell/sharp/releases/download', test: 'https://github.com/lovell/sharp/releases' }
  ],
  sharpLibvips: [
    { name: 'npmmirror', url: 'https://registry.npmmirror.com/-/binary/sharp-libvips', test: 'https://registry.npmmirror.com/-/binary/sharp-libvips' },
    { name: 'github', url: 'https://github.com/lovell/sharp-libvips/releases/download', test: 'https://github.com/lovell/sharp-libvips/releases' }
  ],
  betterSqlite3: [
    { name: 'npmmirror', url: 'https://registry.npmmirror.com/-/binary/better-sqlite3', test: 'https://registry.npmmirror.com/-/binary/better-sqlite3' },
    { name: 'github', url: 'https://github.com/WiseLibs/better-sqlite3/releases/download', test: 'https://github.com/WiseLibs/better-sqlite3/releases' }
  ],
  puppeteer: [
    { name: 'npmmirror', url: 'https://registry.npmmirror.com/-/binary/chromium-browser-snapshots', test: 'https://registry.npmmirror.com/-/binary/chromium-browser-snapshots' },
    { name: 'google', url: 'https://storage.googleapis.com/chromium-browser-snapshots', test: 'https://storage.googleapis.com/chromium-browser-snapshots' }
  ]
};

const TIMEOUT = 3000; // 3秒超时

/**
 * 测试镜像源响应时间
 */
async function testMirror(mirror) {
  const start = Date.now();
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), TIMEOUT);

    const response = await fetch(mirror.test, {
      method: 'HEAD',
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    if (response.ok || response.status === 200 || response.status === 302 || response.status === 301) {
      return { ...mirror, latency: Date.now() - start, available: true };
    }
    return { ...mirror, latency: Infinity, available: false };
  } catch (error) {
    return { ...mirror, latency: Infinity, available: false };
  }
}

/**
 * 选择最快的可用镜像
 */
async function selectBestMirror(mirrors) {
  const results = await Promise.all(mirrors.map(testMirror));
  const available = results.filter(r => r.available);

  if (available.length === 0) {
    // 全部不可用时使用第一个（兜底）
    return mirrors[0];
  }

  // 按延迟排序，选择最快的
  available.sort((a, b) => a.latency - b.latency);
  return available[0];
}

/**
 * 生成 .npmrc 内容
 */
function generateNpmrc(selected) {
  const baseUrl = selected.registry.url.replace(/\/$/, '');
  const lines = [
    '# --- begin auto-generated by setup-mirror.mjs ---',
    `# 生成时间: ${new Date().toISOString()}`,
    '',
    '# npm registry',
    `registry=${selected.registry.url}`,
    '',
    '# 网络超时与重试(避免 GitHub 不稳定时无限等待)',
    'fetch-timeout=60000',
    'fetch-retries=3',
    '',
    '# electron 二进制镜像',
    `electron_mirror=${baseUrl}/-/binary/electron/`,
    `electron_builder_binaries_mirror=${baseUrl}/-/binary/electron-builder-binaries/`,
    '',
    '# puppeteer chromium 镜像',
    `puppeteer_download_base_url=https://cdn.npmmirror.com/binaries/chrome-for-testing`,
    '',
    '# sharp 二进制镜像',
    `sharp_binary_host=${baseUrl}/-/binary/sharp`,
    `sharp_libvips_binary_host=${baseUrl}/-/binary/sharp-libvips`,
    '',
    '# better-sqlite3 二进制镜像',
    `better_sqlite3_binary_host=${baseUrl}/-/binary/better-sqlite3`,
    '',
    '# --- end auto-generated by setup-mirror.mjs ---',
  ];

  return lines.join('\n');
}

/**
 * 配置 git 协议替换
 */
function setupGitProtocol() {
  try {
    // 将 git@github.com: 替换为 https://github.com/
    execSync('git config --global url."https://github.com/".insteadOf "git@github.com:"', { stdio: 'pipe' });
    execSync('git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"', { stdio: 'pipe' });
    console.log('✅ Git 协议替换已配置 (git@github.com → https://github.com)');
  } catch (error) {
    console.warn('⚠️  Git 协议配置失败:', error.message);
  }
}

/**
 * 主函数
 */
async function main() {
  console.log('🔍 检测镜像源可用性...\n');

  const selected = {};

  // 并行测试所有类型
  const types = Object.keys(MIRRORS);
  const results = await Promise.all(
    types.map(async (type) => {
      const best = await selectBestMirror(MIRRORS[type]);
      console.log(`  ${type.padEnd(15)} → ${best.name} (${best.latency === Infinity ? '兜底' : `${best.latency}ms`})`);
      return [type, best];
    })
  );

  results.forEach(([type, mirror]) => {
    selected[type] = mirror;
  });

  console.log('\n📝 生成 .npmrc...');
  const npmrcContent = generateNpmrc(selected);

  // 保留用户自定义配置（自动生成段之外的内容）
  const npmrcPath = '.npmrc';
  if (existsSync(npmrcPath)) {
    const existing = readFileSync(npmrcPath, 'utf-8');
    const autoKeys = [
      'registry=', 'fetch-timeout=', 'fetch-retries=',
      'electron_mirror=', 'electron_builder_binaries_mirror=',
      'puppeteer_download_base_url=', 'puppeteer_download_host=',
      'sharp_binary_host=', 'sharp_libvips_binary_host=',
      'better_sqlite3_binary_host=', 'node-linker=',
    ];
    // 移除自动生成段落（新旧两种格式）和自动生成的键值行
    const customConfig = existing
      .replace(/^# --- begin auto-generated[\s\S]*?# --- end auto-generated[^\n]*\n?/gm, '')
      .replace(/^# 自动生成的镜像配置[\s\S]*?(?=\n\S|$)/gm, '')
      .split('\n')
      .filter(line =>
        !line.includes('# 生成时间:') &&
        !line.includes('# 用户自定义配置') &&
        !line.includes('# npm registry') &&
        !line.includes('# 网络超时') &&
        !line.includes('# electron 二进制镜像') &&
        !line.includes('# puppeteer chromium 镜像') &&
        !line.includes('# sharp 二进制镜像') &&
        !line.includes('# better-sqlite3 二进制镜像') &&
        !autoKeys.some(key => line.startsWith(key)) &&
        line.trim() !== ''
      )
      .join('\n')
      .trim();

    if (customConfig) {
      writeFileSync(npmrcPath, npmrcContent + '\n\n# 用户自定义配置\n' + customConfig + '\n');
    } else {
      writeFileSync(npmrcPath, npmrcContent + '\n');
    }
  } else {
    writeFileSync(npmrcPath, npmrcContent + '\n');
  }

  console.log('✅ .npmrc 已更新\n');

  // 配置 git 协议替换
  setupGitProtocol();

  console.log('\n✨ 镜像配置完成，开始安装依赖...\n');
}

main().catch((error) => {
  console.error('❌ 镜像配置失败:', error.message);
  process.exit(0); // 不阻止安装流程
});
